import * as THREE from 'three';

let last=null;
const state={amount:3};
const $=id=>document.getElementById(id);
function ensureAmountUI(){const page=document.querySelector('[data-workspace-page="hair"]');if(!page||$('hair-amount'))return;const volume=$('hair-volume')?.closest('.row');if(!volume)return;const row=document.createElement('label');row.className='row';row.innerHTML='<span>HAIR AMOUNT</span><input id="hair-amount" type="range" min="1" max="6" step="1" value="3">';volume.after(row);$('hair-amount')?.addEventListener('input',e=>{state.amount=Number(e.target.value);last=null;window.ggHairLab?.rebuildModular?.()})}
function cloneStrand(mesh,dx,dy,dz,sx=.7,sy=1,sz=.8){const c=mesh.clone();c.geometry=mesh.geometry.clone();c.material=mesh.material;c.position.set(dx,dy,dz);c.scale.set(sx,sy,sz);c.renderOrder=mesh.renderOrder;c.frustumCulled=false;c.userData.ggExtraHairStrand=true;return c}
function orientSideRibbon(mesh){const pos=mesh.geometry.attributes.position;if(!pos||pos.count<4)return;for(let i=0;i+1<pos.count;i+=2){const a=new THREE.Vector3(pos.getX(i),pos.getY(i),pos.getZ(i)),b=new THREE.Vector3(pos.getX(i+1),pos.getY(i+1),pos.getZ(i+1)),c=a.clone().add(b).multiplyScalar(.5),half=Math.max(a.distanceTo(b)*.28,.00008);pos.setXYZ(i,c.x,c.y,c.z-half);pos.setXYZ(i+1,c.x,c.y,c.z+half)}pos.needsUpdate=true;mesh.geometry.computeVertexNormals();mesh.geometry.computeBoundingBox();mesh.geometry.computeBoundingSphere()}
function taperAndCurve(mesh,isSide,side){const pos=mesh.geometry.attributes.position;mesh.geometry.computeBoundingBox();const b=mesh.geometry.boundingBox,sy=Math.max(b.max.y-b.min.y,1e-6),center=b.getCenter(new THREE.Vector3());for(let i=0;i<pos.count;i++){let x=pos.getX(i),y=pos.getY(i),z=pos.getZ(i);const t=(b.max.y-y)/sy;/* t=0 root, 1 tip */if(isSide){x=center.x+(x-center.x)*(1-.42*t);x-=side*sy*.055*t*t;z+=sy*.045*Math.sin(t*Math.PI*.75);y+=sy*.025*Math.sin(t*Math.PI);}else{x*=1-.12*t;}pos.setXYZ(i,x,y,z)}pos.needsUpdate=true;mesh.geometry.computeVertexNormals();mesh.geometry.computeBoundingBox();mesh.geometry.computeBoundingSphere()}
function polish(){ensureAmountUI();const modular=window.ggHairLab?.modular;if(modular&&modular!==last){modular.updateMatrixWorld(true);const box=new THREE.Box3().setFromObject(modular),size=box.getSize(new THREE.Vector3()),cap=modular.children.find(o=>o.isMesh&&o.geometry?.type==='SphereGeometry');if(cap){cap.scale.x*=.92;cap.scale.y*=.72;cap.scale.z*=.90;cap.position.y-=Math.max(size.y*.045,.012);cap.position.z-=Math.max(size.z*.018,.004)}const originals=modular.children.filter(o=>o.isMesh&&o!==cap&&o.geometry?.attributes?.position&&!o.userData.ggExtraHairStrand),extras=[];for(const mesh of originals){mesh.geometry.computeBoundingBox();let b=mesh.geometry.boundingBox,center=b.getCenter(new THREE.Vector3()),sx=b.max.x-b.min.x,sy=b.max.y-b.min.y,sz=b.max.z-b.min.z;const side=Math.sign(center.x),isSide=Math.abs(center.x)>size.x*.13,isBack=center.z<-(size.z*.08);if(isSide){orientSideRibbon(mesh);taperAndCurve(mesh,true,side);mesh.geometry.computeBoundingBox();b=mesh.geometry.boundingBox;sy=b.max.y-b.min.y;const count=Math.max(0,state.amount-1);/* More amount means more locks, but each lock gets narrower and staggered instead of occupying the same line. */for(let j=0;j<count;j++){const u=(j+1)/(count+1),signed=j%2===0?-1:1,layer=Math.ceil((j+1)/2),dx=-side*size.x*(.010+.008*layer),dz=signed*size.z*(.018+.012*layer),dy=-sy*(.018+.045*u),width=Math.max(.34,.68-state.amount*.045+j*.012),length=.82+.22*((j*37)%5)/4;const c=cloneStrand(mesh,dx,dy,dz,width,length,.72);c.rotation.y=side*signed*(.025+.018*layer);extras.push(c)}}else if(isBack){taperAndCurve(mesh,false,0);const count=Math.max(0,state.amount-2);for(let j=0;j<count;j++){const k=j-(count-1)/2,u=(j+1)/(count+1);extras.push(cloneStrand(mesh,k*size.x*.018,-sy*(.025+.05*u),-size.z*(.008+.012*Math.abs(k)),Math.max(.38,.70-state.amount*.04),.84+.24*((j*19)%5)/4,.78))}}else{/* Front/top stays front-facing, but at max settings stop it becoming a giant crown. */mesh.scale.y*=state.amount>=5?.88:.94;mesh.scale.x*=state.amount>=5?.92:.96}}
extras.forEach(e=>modular.add(e));console.info('[GG HAIR POLISH] Staggered layered locks.',{amount:state.amount,originals:originals.length,extras:extras.length});last=modular}requestAnimationFrame(polish)}
requestAnimationFrame(polish);window.ggHairPolish={state,setAmount(v){state.amount=Math.max(1,Math.min(6,Number(v)||1));if($('hair-amount'))$('hair-amount').value=state.amount;last=null;window.ggHairLab?.rebuildModular?.()}};console.info('[GG HAIR POLISH] v4 · narrow staggered side/back locks, curved tips, max-density crown control.');