import * as THREE from 'three';
import { FBXLoader } from 'three/addons/loaders/FBXLoader.js';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import JSZip from 'https://cdn.jsdelivr.net/npm/jszip@3.10.1/+esm';

let character=null,hairPivot=null,hairAsset=null,activeUrls=[];const $=id=>document.getElementById(id);const clean=n=>(n||'').toLowerCase().replace(/^mixamorig[:_]?/,'').replace(/[^a-z0-9]/g,'');const findHead=root=>{let h=null;root?.traverse?.(o=>{if(!h&&o.isBone&&clean(o.name)==='head')h=o});return h};const hasSkinnedMesh=root=>{let yes=false;root?.traverse?.(o=>{if(o.isSkinnedMesh)yes=true});return yes};const status=m=>{const e=$('hair-status');if(e)e.textContent=m};const rememberUrl=b=>{const u=URL.createObjectURL(b);activeUrls.push(u);return u};const revokeUrls=()=>{activeUrls.forEach(URL.revokeObjectURL);activeUrls=[]};
function ensureUI(){if($('hair-file'))return;const css=document.createElement('link');css.rel='stylesheet';css.href='./hair-lab.css?v=20260903-hair3';document.head.append(css);const tabs=document.querySelector('.workspace-tabs'),tools=document.querySelector('[data-workspace-tab="tools"]');if(tabs){const b=document.createElement('button');b.type='button';b.className='workspace-tab';b.dataset.workspaceTab='hair';b.textContent='HAIR';tabs.insertBefore(b,tools||null);b.addEventListener('click',()=>{document.querySelectorAll('[data-workspace-tab]').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('[data-workspace-page]').forEach(x=>x.classList.toggle('active',x.dataset.workspacePage==='hair'))})}const body=document.querySelector('.character-workspace .panel-body');if(body){const p=document.createElement('div');p.className='workspace-page';p.dataset.workspacePage='hair';p.innerHTML='<div class="workspace-heading">HAIR LAB · HEAD BONE</div><label class="hair-load">LOAD HAIR / .HP<input id="hair-file" type="file" accept=".hp,.zip,.fbx,.glb" hidden></label><div id="hair-status" class="hair-status">WAITING FOR CHARACTER</div><label class="row"><span>X · LEFT/RIGHT</span><input id="hair-x" type="range" min="-2" max="2" step="0.005" value="0"></label><label class="row"><span>Y · UP/DOWN</span><input id="hair-y" type="range" min="-2" max="2" step="0.005" value="0"></label><label class="row"><span>Z · FRONT/BACK</span><input id="hair-z" type="range" min="-2" max="2" step="0.005" value="0"></label><label class="row"><span>ROT X</span><input id="hair-rx" type="range" min="-180" max="180" step="1" value="0"></label><label class="row"><span>ROT Y</span><input id="hair-ry" type="range" min="-180" max="180" step="1" value="0"></label><label class="row"><span>ROT Z</span><input id="hair-rz" type="range" min="-180" max="180" step="1" value="0"></label><label class="row"><span>SCALE</span><input id="hair-scale" type="range" min="0.05" max="4" step="0.01" value="1"></label><div class="hair-actions"><button id="hair-reset" type="button">RESET FIT</button><button id="hair-remove" type="button">REMOVE</button></div><div class="hair-note">FBX / GLB OR .HP ZIP PACK · ATTACHES TO MIXAMORIG:HEAD · FIT CONTROLS ARE HEAD-LOCAL</div>';body.insertBefore(p,document.querySelector('[data-workspace-page="tools"]'))}}
function setCharacter(root){if(!root||!findHead(root)||!hasSkinnedMesh(root))return false;character=root;status(hairAsset?'HAIR ATTACHED · HEAD TRACKING':'HEAD FOUND · LOAD HAIR');console.info('[GG HAIR] Rigged character bound',root.name||root.type);return true}
const hairPreviousFbxLoad=FBXLoader.prototype.load;FBXLoader.prototype.load=function ggHairCharacterCapture(url,onLoad,onProgress,onError){return hairPreviousFbxLoad.call(this,url,o=>{if(findHead(o)&&hasSkinnedMesh(o))setCharacter(o);onLoad?.(o)},onProgress,onError)};
function discoverCharacter(){if(character&&findHead(character))return character;if(window.ggHairCharacter)setCharacter(window.ggHairCharacter);return character}
function disposeHair(){if(hairPivot?.parent)hairPivot.parent.remove(hairPivot);hairPivot=null;hairAsset=null;status(character?'HEAD FOUND · LOAD HAIR':'WAITING FOR CHARACTER')}
function disposeUrls(){revokeUrls()}
function toonify(root){root.traverse(o=>{if(!o.isMesh)return;o.castShadow=true;o.receiveShadow=true;o.frustumCulled=false;const mats=Array.isArray(o.material)?o.material:[o.material];const out=mats.map(m=>{if(!m)return new THREE.MeshStandardMaterial({color:0x17151a,roughness:.72});const n=m.clone();n.roughness=Math.max(.45,n.roughness??.7);n.metalness=Math.min(.25,n.metalness??0);n.side=THREE.DoubleSide;return n});o.material=out.length===1?out[0]:out})}
function syncUI(){if(!hairPivot)return;const d=THREE.MathUtils.radToDeg,vals={'hair-x':hairPivot.position.x,'hair-y':hairPivot.position.y,'hair-z':hairPivot.position.z,'hair-rx':d(hairPivot.rotation.x),'hair-ry':d(hairPivot.rotation.y),'hair-rz':d(hairPivot.rotation.z),'hair-scale':hairPivot.scale.x};for(const[id,v]of Object.entries(vals))if($(id))$(id).value=v}
function fitToHead(root,name='HAIR'){discoverCharacter();const head=findHead(character);if(!head){status('NO LIVE CHARACTER HEAD · RELOAD BASE');console.warn('[GG HAIR] Hair parsed, but no live Mixamo Head bone was found');return}disposeHair();hairPivot=new THREE.Group();hairPivot.name='GG_HairPivot';hairPivot.userData.ggHairAsset=true;root.userData.ggHairAsset=true;hairAsset=root;toonify(root);root.position.set(0,0,0);root.scale.set(1,1,1);root.rotation.set(0,0,0);root.updateMatrixWorld(true);const box=new THREE.Box3().setFromObject(root),size=box.getSize(new THREE.Vector3()),center=box.getCenter(new THREE.Vector3());const charBox=new THREE.Box3().setFromObject(character),charH=charBox.getSize(new THREE.Vector3()).y,targetH=Math.max(.001,charH*.22),s=size.y>1e-6?targetH/size.y:1;root.scale.setScalar(s);root.position.copy(center).multiplyScalar(-s);root.updateMatrixWorld(true);hairPivot.add(root);head.add(hairPivot);hairPivot.position.set(0,charH*.018,0);hairPivot.rotation.set(0,0,0);hairPivot.scale.setScalar(1);syncUI();status(`${name} · ATTACHED · AUTO SCALE ${s.toFixed(4)}`);document.querySelector('[data-workspace-tab="hair"]')?.click();console.info('[GG HAIR] Attached',name,'to',head.name,{rawSize:size.toArray(),rawCenter:center.toArray(),autoScale:s,pivot:hairPivot.position.toArray()})}
async function tex(z,srgb=false){const t=await new THREE.TextureLoader().loadAsync(rememberUrl(await z.async('blob')));t.flipY=false;if(srgb)t.colorSpace=THREE.SRGBColorSpace;return t}
async function loadHairPack(file){discoverCharacter();status('OPENING .HP / ZIP HAIRPACK...');disposeUrls();const zip=await JSZip.loadAsync(file),entries=Object.values(zip.files).filter(f=>!f.dir),by=r=>entries.find(f=>r.test(f.name.toLowerCase())),model=by(/\.(fbx|glb)$/);console.info('[GG HAIR] Hairpack files',entries.map(f=>f.name));if(!model)throw new Error('NO FBX/GLB IN HAIRPACK');status(`FOUND ${model.name.split('/').pop()} · READING...`);const base=by(/(?:texture|basecolor|base_color|albedo|diffuse)\.png$/),normal=by(/normal.*\.png$/),rough=by(/roughness.*\.png$/),metal=by(/metallic.*\.png$/),mb=await model.async('blob');let root;if(model.name.toLowerCase().endsWith('.glb'))root=(await new GLTFLoader().loadAsync(rememberUrl(mb))).scene;else root=new FBXLoader().parse(await mb.arrayBuffer(),'');status('MODEL READ · APPLYING HAIR MATERIALS...');const[map,nmap,rmap,mmap]=await Promise.all([base?tex(base,true):null,normal?tex(normal):null,rough?tex(rough):null,metal?tex(metal):null]);root.traverse(o=>{if(o.isMesh)o.material=new THREE.MeshStandardMaterial({color:0xffffff,map,normalMap:nmap,roughnessMap:rmap,metalnessMap:mmap,roughness:.72,metalness:.04,side:THREE.DoubleSide})});fitToHead(root,file.name.replace(/\.(hp|zip)$/i,''))}
async function loadLoose(file){discoverCharacter();disposeUrls();const url=rememberUrl(file);status(`LOADING ${file.name.toUpperCase()}...`);const root=/\.glb$/i.test(file.name)?(await new GLTFLoader().loadAsync(url)).scene:await new FBXLoader().loadAsync(url);fitToHead(root,file.name.replace(/\.[^.]+$/,''))}
async function loadFile(file){if(!file)return;try{if(/\.(hp|zip)$/i.test(file.name))await loadHairPack(file);else if(/\.(fbx|glb)$/i.test(file.name))await loadLoose(file);else status('USE .HP / .ZIP / .FBX / .GLB')}catch(e){console.error('[GG HAIR]',e);status(`HAIR LOAD FAILED · ${e.message}`)}}
function bindRange(id,fn){$(id)?.addEventListener('input',e=>{if(hairPivot)fn(Number(e.target.value))})}function setup(){ensureUI();$('hair-file')?.addEventListener('change',async e=>{const input=e.target,file=input.files?.[0];await loadFile(file);input.value=''});bindRange('hair-x',v=>hairPivot.position.x=v);bindRange('hair-y',v=>hairPivot.position.y=v);bindRange('hair-z',v=>hairPivot.position.z=v);bindRange('hair-rx',v=>hairPivot.rotation.x=THREE.MathUtils.degToRad(v));bindRange('hair-ry',v=>hairPivot.rotation.y=THREE.MathUtils.degToRad(v));bindRange('hair-rz',v=>hairPivot.rotation.z=THREE.MathUtils.degToRad(v));bindRange('hair-scale',v=>hairPivot.scale.setScalar(v));$('hair-remove')?.addEventListener('click',disposeHair);$('hair-reset')?.addEventListener('click',()=>{if(!hairPivot||!character)return;const h=new THREE.Box3().setFromObject(character).getSize(new THREE.Vector3()).y;hairPivot.position.set(0,h*.018,0);hairPivot.rotation.set(0,0,0);hairPivot.scale.setScalar(1);syncUI();status('HAIR FIT RESET')});discoverCharacter();status(character?'HEAD FOUND · LOAD HAIR':'WAITING FOR CHARACTER')}
window.ggHairLab={get character(){return character},get hair(){return hairPivot},loadFile,remove:disposeHair,setCharacter,getFit(){return hairPivot?{position:hairPivot.position.toArray(),rotation:[hairPivot.rotation.x,hairPivot.rotation.y,hairPivot.rotation.z],scale:hairPivot.scale.x}:null}};if(window.ggHairCharacter)setCharacter(window.ggHairCharacter);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',setup);else setup();console.info('[GG HAIR] Head-bone Hair Lab v4 armed · FBX character capture · corrected Meshy centering');