import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
import { OrbitControls } from 'https://cdn.jsdelivr.net/npm/three@0.180.0/examples/jsm/controls/OrbitControls.js';
import { GLTFLoader } from 'https://cdn.jsdelivr.net/npm/three@0.180.0/examples/jsm/loaders/GLTFLoader.js';
import { FBXLoader } from 'https://cdn.jsdelivr.net/npm/three@0.180.0/examples/jsm/loaders/FBXLoader.js';
import { toCreasedNormals } from 'three/addons/utils/BufferGeometryUtils.js';
import { DecalSystem } from './decals.js?v=20260829-0240';

const app=document.querySelector('#app'),canvas=document.querySelector('#game'),status=document.querySelector('#status'),modelName=document.querySelector('#model-name'),animInfo=document.querySelector('#anim-info'),settings=document.querySelector('#settings'),settingsToggle=document.querySelector('#settings-toggle'),smoothToggle=document.querySelector('#smooth-model'),smoothingSlider=document.querySelector('#smoothing');
const renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true});renderer.setPixelRatio(1);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;
const scene=new THREE.Scene();scene.fog=new THREE.FogExp2(0xf1c0c7,.018);
const camera=new THREE.PerspectiveCamera(45,16/9,.025,100),homePosition=new THREE.Vector3(5.8,3.4,7.2),homeTarget=new THREE.Vector3(0,1.6,0);camera.position.copy(homePosition);
const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.target.copy(homeTarget);controls.minDistance=.18;controls.maxDistance=15;controls.update();
const clock=new THREE.Clock();

function makeGradientMap(steps=3){const data=new Uint8Array(steps*4);for(let i=0;i<steps;i++){const v=Math.round(70+(185*i)/Math.max(1,steps-1));data.set([v,v,v,255],i*4)}const t=new THREE.DataTexture(data,steps,1,THREE.RGBAFormat);t.minFilter=t.magFilter=THREE.NearestFilter;t.generateMipmaps=false;t.needsUpdate=true;return t}
let gradientMap=makeGradientMap(3),character=null,sourceUrl=null,mixer=null,currentAction=null,paused=false,hasSkinned=false;
const meshes=[],outlines=[],gltfLoader=new GLTFLoader(),fbxLoader=new FBXLoader();
const floor=new THREE.Mesh(new THREE.PlaneGeometry(40,40),new THREE.MeshToonMaterial({color:0xfff6e9,gradientMap:makeGradientMap(2)}));floor.rotation.x=-Math.PI/2;floor.receiveShadow=true;scene.add(floor);
const grid=new THREE.GridHelper(40,20,0x161218,0x302a2d);grid.position.y=.01;scene.add(grid);
const keyLight=new THREE.DirectionalLight(0xfff0db,2.5);keyLight.position.set(-5,10,6);keyLight.castShadow=true;scene.add(keyLight);
const ambientLight=new THREE.HemisphereLight(0xffe0e0,0x4a3c67,1.8);scene.add(ambientLight);
const rimLight=new THREE.DirectionalLight(0xded4ff,1.4);rimLight.position.set(7,5,-7);scene.add(rimLight);
function flash(message,ms=1400){status.textContent=message;status.classList.add('show');clearTimeout(flash.timer);flash.timer=setTimeout(()=>status.classList.remove('show'),ms)}

const decalSystem=new DecalSystem({panel:document.querySelector('#decals'),featureSelect:document.querySelector('#decal-feature'),childSelect:document.querySelector('#decal-child'),controls:{visible:document.querySelector('#decal-visible'),x:document.querySelector('#decal-x'),y:document.querySelector('#decal-y'),scaleX:document.querySelector('#decal-scale-x'),scaleY:document.querySelector('#decal-scale-y'),rotation:document.querySelector('#decal-rotation'),variant:document.querySelector('#decal-variant')},flash});window.ggDecals=decalSystem;

function disposeCharacter(){if(currentAction)currentAction.stop();mixer?.stopAllAction();mixer=null;currentAction=null;paused=false;if(character)scene.remove(character);outlines.splice(0).forEach(o=>{o.parent?.remove(o);o.material?.dispose?.()});meshes.splice(0).forEach(mesh=>{mesh.userData.smoothGeometry?.dispose?.();mesh.userData.toonMaterial?.dispose?.()});character=null;hasSkinned=false;animInfo.textContent='NO ANIMATION'}
function cloneToonMaterial(o){return new THREE.MeshToonMaterial({color:o?.color?.clone?.()||new THREE.Color(0xffffff),map:o?.map||null,normalMap:o?.normalMap||null,transparent:Boolean(o?.transparent),opacity:o?.opacity??1,side:o?.side??THREE.FrontSide,gradientMap,skinning:true})}
function buildOutline(mesh){if(mesh.isSkinnedMesh)return;const m=new THREE.MeshBasicMaterial({color:0x08080a,side:THREE.BackSide}),o=new THREE.Mesh(mesh.geometry,m);o.position.copy(mesh.position);o.quaternion.copy(mesh.quaternion);o.scale.setScalar(Number(document.querySelector('#edge').value));o.visible=document.querySelector('#outline').checked;o.renderOrder=-1;mesh.parent.add(o);outlines.push(o)}
function applyCelMode(){const e=document.querySelector('#cel').checked;meshes.forEach(m=>m.material=e?m.userData.toonMaterial:m.userData.originalMaterial)}
function rebuildToonMaterials(){meshes.forEach(m=>{m.userData.toonMaterial?.dispose?.();m.userData.toonMaterial=cloneToonMaterial(m.userData.originalMaterial)});applyCelMode()}
function buildSmoothGeometry(m,d){if(m.isSkinnedMesh)return;m.userData.smoothGeometry?.dispose?.();m.userData.smoothGeometry=toCreasedNormals(m.userData.originalGeometry,THREE.MathUtils.degToRad(Number(d)))}
function applyModelSmoothing(rebuild=false){const e=smoothToggle.checked,d=Number(smoothingSlider.value);smoothingSlider.disabled=!e;meshes.forEach(m=>{if(m.isSkinnedMesh){m.geometry=m.userData.originalGeometry;return}if(e&&(rebuild||!m.userData.smoothGeometry||m.userData.smoothingDegrees!==d)){buildSmoothGeometry(m,d);m.userData.smoothingDegrees=d}m.geometry=e?m.userData.smoothGeometry:m.userData.originalGeometry})}
function fitCharacter(root){root.scale.setScalar(1);root.position.set(0,0,0);root.updateMatrixWorld(true);const b=new THREE.Box3().setFromObject(root),s=b.getSize(new THREE.Vector3()),h=3.8;root.scale.setScalar(h/Math.max(s.y,.001));root.updateMatrixWorld(true);const f=new THREE.Box3().setFromObject(root),c=f.getCenter(new THREE.Vector3());root.position.x-=c.x;root.position.z-=c.z;root.position.y-=f.min.y;root.updateMatrixWorld(true);homeTarget.set(0,h*.52,0);homePosition.set(5.6,3.3,7.4)}
function getHeadWorldPosition(){if(character){const head=character.getObjectByName('mixamorig:Head')||character.getObjectByName('mixamorigHead')||character.getObjectByName('Head');if(head)return head.getWorldPosition(new THREE.Vector3())}return character?new THREE.Box3().setFromObject(character).getCenter(new THREE.Vector3()):new THREE.Vector3()}
function setCameraPreset(mode,announce=true){if(!character){camera.position.copy(homePosition);controls.target.copy(homeTarget);controls.update();return}const b=new THREE.Box3().setFromObject(character),s=b.getSize(new THREE.Vector3()),c=b.getCenter(new THREE.Vector3());let target=c.clone(),distance=6.8;if(mode==='face'){target=getHeadWorldPosition();distance=Math.max(.4,s.y*.13)}else if(mode==='torso'){target.set(c.x,b.min.y+s.y*.68,c.z);distance=Math.max(1.55,s.y*.55)}else{target.set(c.x,b.min.y+s.y*.5,c.z);distance=Math.max(5.2,s.y*1.75);mode='body'}controls.target.copy(target);camera.position.set(target.x+distance*.06,target.y+distance*.015,target.z+distance);camera.lookAt(target);controls.update();if(announce)flash(`${mode.toUpperCase()} CAMERA`)}

function installCharacter(root,animations,label){disposeCharacter();character=root;scene.add(character);character.traverse(o=>{if(!o.isMesh)return;o.castShadow=true;o.receiveShadow=true;o.frustumCulled=false;o.userData.originalGeometry=o.geometry;o.userData.originalMaterial=o.material;o.userData.toonMaterial=cloneToonMaterial(o.material);if(o.isSkinnedMesh)hasSkinned=true;meshes.push(o)});applyModelSmoothing(true);meshes.forEach(buildOutline);fitCharacter(character);applyCelMode();if(!hasSkinned)decalSystem.attach(character);mixer=new THREE.AnimationMixer(character);setCameraPreset('body',false);modelName.textContent=`${label.toUpperCase()} · ${hasSkinned?'RIGGED':'STATIC'}`;flash(`${label} · ${meshes.length} MESH · ${hasSkinned?'SKELETON FOUND':'NO SKELETON'}`,2600);if(animations?.length)playClip(animations[0],`${label} embedded`)}
function loadModelUrl(url,label){modelName.textContent=`LOADING ${label.toUpperCase()}...`;const isFbx=/\.fbx(?:$|\?)/i.test(url)||/\.fbx$/i.test(label);if(isFbx)fbxLoader.load(url,o=>installCharacter(o,o.animations||[],label),undefined,loadError);else gltfLoader.load(url,g=>installCharacter(g.scene,g.animations||[],label),undefined,loadError)}
function loadError(e){console.error(e);modelName.textContent='MODEL LOAD FAILED';flash('MODEL LOAD FAILED · CHECK CONSOLE',3200)}
function playClip(clip,label='animation'){if(!character||!mixer||!clip){flash('NO RIG / CLIP TO PLAY',2200);return}mixer.stopAllAction();currentAction=mixer.clipAction(clip);currentAction.reset().setLoop(THREE.LoopRepeat,Infinity).play();paused=false;animInfo.textContent=`${label.toUpperCase()} · ${clip.duration.toFixed(2)}s · ${clip.tracks.length} TRACKS`;document.querySelector('#anim-pause').textContent='PAUSE';flash(`PLAYING ${label}`,2200)}
function loadAnimation(url,label){if(!character||!hasSkinned){flash('LOAD A RIGGED BASE FIRST',2200);return}animInfo.textContent=`LOADING ${label.toUpperCase()}...`;fbxLoader.load(url,o=>{const clip=o.animations?.[0];if(!clip){animInfo.textContent='NO CLIP FOUND';flash('FBX HAS NO ANIMATION CLIP',2600);return}playClip(clip,label)},undefined,e=>{console.error(e);animInfo.textContent='ANIMATION LOAD FAILED';flash('ANIMATION LOAD FAILED',3000)})}

const modelFile=document.querySelector('#model-file');modelFile.addEventListener('change',()=>{const f=modelFile.files?.[0];if(!f)return;if(sourceUrl)URL.revokeObjectURL(sourceUrl);sourceUrl=URL.createObjectURL(f);loadModelUrl(sourceUrl,f.name)});
const baseModel=document.querySelector('#base-model');baseModel.addEventListener('change',()=>{const female=baseModel.value==='female';loadModelUrl(female?'./character-creator/Basemodel._f.fbx':'./character-creator/Basemodel.fbx',female?'Female Basemodel.fbx':'Male Basemodel.fbx')});
document.querySelector('#test-stance').addEventListener('click',()=>loadAnimation('./character-creator/Anim/boxing/StanceAnim.fbx','Boxing Stance'));
document.querySelector('#anim-pause').addEventListener('click',e=>{if(!currentAction)return;paused=!paused;mixer.timeScale=paused?0:1;e.currentTarget.textContent=paused?'RESUME':'PAUSE';flash(paused?'ANIMATION PAUSED':'ANIMATION RESUMED')});
document.querySelector('#anim-stop').addEventListener('click',()=>{mixer?.stopAllAction();currentAction=null;animInfo.textContent='STOPPED';flash('ANIMATION STOPPED')});
loadModelUrl('./character-creator/Basemodel.fbx','Male Basemodel.fbx');

settingsToggle.addEventListener('click',()=>{const c=settings.classList.toggle('collapsed');settingsToggle.setAttribute('aria-expanded',String(!c));settingsToggle.querySelector('.toggle-mark').textContent=c?'▶':'◀'});document.querySelectorAll('[data-camera]').forEach(b=>b.addEventListener('click',()=>setCameraPreset(b.dataset.camera)));
smoothToggle.addEventListener('change',()=>{applyModelSmoothing(false);flash(hasSkinned?'SKINNED MESH PRESERVES RIG GEOMETRY':`MODEL SMOOTHING ${smoothToggle.checked?'ON':'OFF'}`)});let smoothingTimer;smoothingSlider.addEventListener('input',()=>{clearTimeout(smoothingTimer);smoothingTimer=setTimeout(()=>applyModelSmoothing(true),60)});
const cel=document.querySelector('#cel');cel.addEventListener('change',()=>{applyCelMode();flash(`CEL SHADING ${cel.checked?'ON':'OFF'}`)});const outlineToggle=document.querySelector('#outline');outlineToggle.addEventListener('change',()=>{outlines.forEach(o=>o.visible=outlineToggle.checked);flash(hasSkinned?'RIG TEST: STATIC OUTLINE DISABLED':`OUTLINE ${outlineToggle.checked?'ON':'OFF'}`)});const bands=document.querySelector('#bands');bands.addEventListener('change',()=>{gradientMap.dispose();gradientMap=makeGradientMap(Number(bands.value));rebuildToonMaterials()});const edge=document.querySelector('#edge');edge.addEventListener('input',()=>outlines.forEach(o=>o.scale.setScalar(Number(edge.value))));document.querySelector('#key').addEventListener('input',e=>keyLight.intensity=Number(e.target.value));document.querySelector('#ambient').addEventListener('input',e=>ambientLight.intensity=Number(e.target.value));document.querySelector('#rim').addEventListener('change',e=>rimLight.visible=e.target.checked);
function getAutoRenderScale(){const m=navigator.deviceMemory||4,c=navigator.hardwareConcurrency||4;if(m<=2||c<=4)return .5;if(m<=4||c<=6)return .75;if(m>=8&&c>=12)return 1.25;return 1}let renderScaleMode=localStorage.getItem('gg-render-scale')||'auto';const renderScaleSelect=document.querySelector('#render-scale');renderScaleSelect.value=[...renderScaleSelect.options].some(o=>o.value===renderScaleMode)?renderScaleMode:'auto';renderScaleSelect.addEventListener('change',()=>{renderScaleMode=renderScaleSelect.value;localStorage.setItem('gg-render-scale',renderScaleMode);resize()});function resolvedRenderScale(){return renderScaleMode==='auto'?getAutoRenderScale():Number(renderScaleMode)}function chooseUIProfile(w,h){const a=w/Math.max(h,1),t=matchMedia('(pointer: coarse)').matches||navigator.maxTouchPoints>0;if(t&&w<=900&&h>w)return'phone-portrait';if(t&&h<=650)return'phone-landscape';if(w<=900)return h>w?'phone-portrait':'phone-landscape';if(w<=1180||h<=720)return'tablet';if(w<=1500||h<=850)return'compact';if(a>=2.05&&w>=1800)return'ultrawide';return'desktop'}function adaptUI(w,h){const p=chooseUIProfile(w,h);app.dataset.uiProfile=p;app.dataset.inputMode=matchMedia('(pointer: coarse)').matches?'touch':'pointer'}function resetCamera(){setCameraPreset('body')}app.addEventListener('keydown',e=>{if(e.target.matches('input,select,button'))return;const k=e.key.toLowerCase();if(k==='r')resetCamera();if(k==='f')setCameraPreset('face');if(k==='h')document.querySelectorAll('.panel,.jp-card,.logo,.version,.topbar').forEach(el=>el.hidden=!el.hidden)});function resize(){const w=Math.max(1,app.clientWidth),h=Math.max(1,app.clientHeight),s=resolvedRenderScale();renderer.setSize(Math.round(w*s),Math.round(h*s),false);canvas.style.width=`${w}px`;canvas.style.height=`${h}px`;camera.aspect=w/h;camera.updateProjectionMatrix();adaptUI(w,h)}addEventListener('resize',resize);addEventListener('orientationchange',()=>setTimeout(resize,50));resize();
(function animate(){requestAnimationFrame(animate);const dt=clock.getDelta();if(mixer)mixer.update(dt);controls.update();renderer.render(scene,camera)})();